version: "3.2"
services:
  syslog-ng:
    build: ./services/syslog-ng
    ports:
      - "6514:6514"

    volumes:
      - type: bind
        source: ./services/syslog-ng/ess.log
        target: /var/log/ess.log

    command: ["--no-caps"]

  mysql:
    build: ./services/mysql
    expose:
      - "3306"

    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
        consistency: consistent

  mail-api:
    build: https://github.com/cjpf/barracuda-syslog-api.git#dev
    expose:
      - "5000"

    depends_on: 
      - mysql
      - syslog-ng
    links:
      - mysql:db
    environment:
      DATABASE_URL: "mysql+pymysql://api:api@db/cuda_api?charset=utf8mb4"

    volumes:
      - type: bind
        source: ./services/syslog-ng/ess.log
        target: /home/api/app/ess.log

  nginx:
    build: ./services/nginx
    ports:
      - "80:80"
    depends_on:
      - mail-api

volumes:
  mysql-data:
