version: "3.2"
services:
  syslog-ng:
    image: balabit/syslog-ng:latest
    ports:
      - 6514:6514
    volumes:
      - type: bind
        source: ./syslog-ng/conf/syslog-ng.conf
        target: /etc/syslog-ng/syslog-ng.conf

      - type: bind
        source: ./syslog-ng/conf/ca.d
        target: /etc/syslog-ng/ca.d

      - type: bind
        source: ./syslog-ng/conf/cert.d
        target: /etc/syslog-ng/cert.d

      - type: bind
        source: ./syslog-ng/log/ess.log
        target: /var/log/ess.log

      - type: volume
        source: syslog-ng-data
        target: /var/log
        consistency: consistent

    command: ["--no-caps"]

  mysql:
    image: mysql:8.0.19
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cuda_api"
      MYSQL_USER: "api"
      MYSQL_PASSWORD: "api"

    volumes:
      - type: bind
        source: ./mysql/mysqld_charset.cnf
        target: /etc/mysql/conf.d/mysqld_charset.cnf
      
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
        consistency: consistent

  # mail-api:
  #   build: https://github.com/cjpf/barracuda-syslog-api.git#dev
  #   links:
  #     - mysql:db
  #   environment:
  #     DATABASE_URL: mysql+pymysql://api:api@db/cuda_api
  #   # volumes:
  #     # - "./syslog-ng/logs/mail/ess.log:/home/api/app/ess.log"
    
volumes:
  syslog-ng-data:
  mysql-data:
# networks: