version: "3.2"
services:
  syslog-ng:
    image: balabit/syslog-ng:latest
    ports:
      - "6514:6514"

    volumes:
      - type: bind
        source: ./syslog-ng/conf/syslog-ng.conf
        target: /etc/syslog-ng/syslog-ng.conf

      - type: bind
        source: ${CA_PATH}
        target: /etc/syslog-ng/ca.d

      - type: bind
        source: ${CERT_PATH}
        target: /etc/syslog-ng/cert.d

      - type: bind
        source: ./syslog-ng/log/ess.log
        target: /var/log/ess.log

    command: ["--no-caps"]

  mysql:
    build: ./services/mysql
    expose:
      - "3306"

    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
        consistency: consistent

  mail-api:
    build: https://github.com/cjpf/barracuda-syslog-api.git#dev
    # ports:
    #   - 5000:5000
    expose:
      - "5000"

    depends_on: 
      - mysql
      - syslog-ng
    links:
      - mysql:db
    environment:
      DATABASE_URL: mysql+pymysql://${DB_USER}:${DB_USER_PASSWORD}@db/cuda_api

    volumes:
      - type: bind
        source: ./syslog-ng/log/ess.log
        target: /home/api/app/ess.log

  nginx:
    build: ./services/nginx
    ports:
      - "80:80"
    depends_on:
      - mail-api

volumes:
  mysql-data:
