version: "3.2"
services:
  syslog-ng:
    build: 
      context: ./
      dockerfile: ./services/syslog-ng/Dockerfile
    ports:
      - "6514:6514"

    volumes:
      - type: bind
        source: ./services/syslog-ng/ess.log
        target: /var/log/ess.log

    command: ["--no-caps"]

  mysql:
    build: ./services/mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cuda_api
      MYSQL_USER: api
      MYSQL_PASSWORD: api

  mail-api:
    build: https://github.com/cjpf/barracuda-syslog-api.git#dev
    expose:
      - "5000"

    depends_on: 
      - mysql
      - syslog-ng
      - mail
    links:
      - mysql:db
      - mail:out-mail
    environment:
      DATABASE_URL: "mysql+pymysql://api:api@db/cuda_api?charset=utf8mb4"
      MAIL_SERVER: out-mail
      MAIL_PORT: "25"

    volumes:
      - type: bind
        source: ./services/syslog-ng/ess.log
        target: /home/api/app/ess.log

  mail:
    image: bytemark/smtp
    restart: always
    # environment:
    #   RELAY_HOST: smtp.example.com
    #   RELAY_PORT: "587"
    #   RELAY_USERNAME: bob@example.com
    #   RELAY_PASSWORD: secret

  nginx:
    build:
      context: ./
      dockerfile: ./services/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mail-api

volumes:
  mysql-data:
